version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - frontend
    volumes:
      - ./config/docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/ponydays

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs

  php:
    build:
      dockerfile: ./config/docker/php/Dockerfile
      context: .
    links:
      - mysql
    volumes:
      - ./:/var/www/ponydays

  frontend:
    build:
      dockerfile: ./config/docker/frontend/Dockerfile
      context: .
    volumes:
      - ./:/var/www/ponydays
    command: sh -c "yarn && yarn webpack:dev"

  mysql:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    env_file:
      - config/docker/.env
    volumes:
      - ./docker_data/db:/var/lib/mysql